services:
  - type: web
    name: icegods-telegram-bot
    env: python
    plan: free
    region: frankfurt

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      python3 start_icegods.py

    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_ADMIN_ID
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: INFURA_API_KEY
        sync: false
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: CMC_API_KEY
        sync: false
      - key: COINGECKO_API_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: USE_WEBHOOK
        value: "True"
      - key: PORT
        value: "5000"
